# Generated by Django 2.2.6 on 2019-10-14 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0003_auto_20191014_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegiftcard',
            name='user_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
