# Generated by Django 2.2.6 on 2019-10-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0004_activegiftcard_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegiftcard',
            name='merchant_name',
            field=models.CharField(max_length=100),
        ),
    ]
