# Generated by Django 2.2.6 on 2019-10-14 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_auto_20191014_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegiftcard',
            name='sender_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_key', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
