# Generated by Django 2.2.6 on 2019-10-14 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_giftcardimage_merchant_name'),
        ('authent', '0006_activegiftcard_sender_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartGiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100)),
                ('current_card_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('receiver_username', models.EmailField(max_length=150)),
                ('card_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.GiftCardImage')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cart_cards',
            field=models.ManyToManyField(blank=True, to='authent.CartGiftCard'),
        ),
    ]
