# Generated by Django 2.2.6 on 2019-10-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0007_auto_20191014_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartgiftcard',
            name='receiver_username',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
