# Generated by Django 2.2.6 on 2019-10-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0010_cartgiftcard_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgiftcard',
            name='stripe_acct_id',
            field=models.CharField(default='TEST', max_length=200),
            preserve_default=False,
        ),
    ]
