# Generated by Django 2.2.6 on 2019-10-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0011_cartgiftcard_stripe_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartgiftcard',
            name='stripe_acct_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
