# Generated by Django 2.2.6 on 2019-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0012_auto_20191019_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegiftcard',
            name='stripe_acct_id',
            field=models.CharField(default='t', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
