# Generated by Django 2.2.6 on 2019-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0016_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgiftcard',
            name='transfer_group',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
