# Generated by Django 2.2.6 on 2019-11-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0017_cartgiftcard_transfer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='transfer_group',
            field=models.CharField(default='UNSET', max_length=500),
        ),
    ]
