# Generated by Django 2.2.6 on 2019-11-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0018_auto_20191107_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected_acct_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
