# Generated by Django 2.2.6 on 2019-12-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
        ('authent', '0019_user_connected_acct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='qr.Transaction'),
        ),
    ]
