# Generated by Django 2.2.6 on 2019-10-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewableGiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('max_value', models.IntegerField()),
                ('card_image', models.ImageField(height_field=570, upload_to='card-images/', width_field=895)),
            ],
        ),
    ]
