# Generated by Django 2.2.6 on 2019-10-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewablegiftcard',
            name='card_image',
            field=models.ImageField(upload_to='card-images/'),
        ),
    ]
