# Generated by Django 2.2.6 on 2019-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_viewablegiftcard_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewablegiftcard',
            name='one_liner',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
