# Generated by Django 2.2.6 on 2019-10-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_viewablegiftcard_one_liner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewablegiftcard',
            name='merchant_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
