# Generated by Django 2.2.6 on 2019-10-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_viewablegiftcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewablegiftcard',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
