# Generated by Django 2.2.6 on 2019-10-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20191012_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(upload_to='card-images/')),
            ],
        ),

    ]
