# Generated by Django 2.2.6 on 2019-10-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20191013_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewablegiftcard',
            old_name='card_image',
            new_name='card_key',
        ),
    ]
