# Generated by Django 2.2.6 on 2019-10-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20191013_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewablegiftcard',
            name='card_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.GiftCardImages'),
        ),
    ]
