# Generated by Django 2.2.6 on 2019-10-13 22:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('frontend', '0011_auto_20191013_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiftCardImages',
            new_name='GiftCardImage',
        ),
    ]
