# Generated by Django 2.2.6 on 2019-10-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20191013_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardimage',
            name='merchant_name',
            field=models.CharField(default='222', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
