# Generated by Django 2.2.6 on 2019-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_giftcardimage_merchant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewablegiftcard',
            name='stripe_acct_id',
            field=models.CharField(default='FAKE', max_length=200),
            preserve_default=False,
        ),
    ]
