# Generated by Django 2.2.6 on 2019-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_viewablegiftcard_stripe_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewablegiftcard',
            name='stripe_acct_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
