# Generated by Django 2.2.6 on 2019-10-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20191019_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewablegiftcard',
            old_name='featured',
            new_name='featured1',
        ),
        migrations.AddField(
            model_name='viewablegiftcard',
            name='featured2',
            field=models.BooleanField(default=False),
        ),
    ]
